#!/bin/bash
IMAGES="/home/james/Documents/projects/scryfall-fetch/images/*.png"
function fetch_cards(){
	i=0
	while [ ! $i -gt 5 ]
	do
		node fetch-basic.js
		((i++))
	done
}

function wallpaper_set(){
	valid=1
	for filename in $IMAGES
	do
		if ! grep -Fxq "$filename" lands-displayed.txt
		then
			xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/last-image -s $filename
			echo $filename >> lands-displayed.txt
			valid=0
			echo "Background changed."
			break
		fi
	done
	if [ $valid == 1 ]
	then
		refresh_cards
	fi
}

function refresh_cards(){
	rm ./images/*
	rm ./card-info/*
	rm lands-displayed.txt
	fetch_cards
	wallpaper_set
}

function wall_info(){
	cat lands-displayed.txt
}

while [ ! $# -eq 0 ]
do
	case "$1" in
		--displayed | -D)
			wall_info
			exit
			;;
		--refresh | -R)
			refresh_cards
			exit
			;;
	esac
	shift
	exit 0
done

wallpaper_set
exit 0
